services:
  - type: web
    name: prismtalk-realtime
    runtime: node
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeployTrigger: commit
    healthCheckPath: /health
    envVars:
      - key: FRONTEND_BASE_URL
        value: https://pau7196533-lang.github.io/multitranslator/public/
      - key: CORS_ORIGIN
        value: https://pau7196533-lang.github.io,https://mulittranslator.netlify.app
      - key: HTTPS
        value: "false"
      - key: PUBLIC_BASE_URL
        value: https://prismtalk-realtime.onrender.com
      - key: GOOGLE_TRANSLATE_API_KEY
        sync: false
      - key: GOOGLE_SPEECH_API_KEY
        sync: false
